version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.appone.tech'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.appone.tech'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8001:80'
      - '4434:443'
      - '222:22'
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data/data:/var/opt/gitlab'
    shm_size: '256m'
