#In your domain host
add mx
txt -> v=spf1 mx ~all

mkdir /iredmail         # Create a new directory or use any directory
                        # you prefer. `/iredmail/` is just an example
cd /iredmail
touch iredmail-docker.conf

  echo HOSTNAME=mail.mydomain.com >> iredmail-docker.conf
echo FIRST_MAIL_DOMAIN=mydomain.com >> iredmail-docker.conf
echo FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=my-secret-password >> iredmail-docker.conf
echo MLMMJADMIN_API_TOKEN=$(openssl rand -base64 32) >> iredmail-docker.conf
echo ROUNDCUBE_DES_KEY=$(openssl rand -base64 24) >> iredmail-docker.conf

cd /iredmail
mkdir -p data/{backup-mysql,clamav,custom,imapsieve_copy,mailboxes,mlmmj,mlmmj-archive,mysql,sa_rules,ssl,postfix_queue}


ŸêAfter Running the container 
docker exec -it iredmail amavisd-new showkeys
#The output would be something like this
dkim._domainkey.mydomain.com.   3600 TXT (
  "v=DKIM1; p="
  "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYArsr2BKbdhv9efugByf7LhaK"
  "txFUt0ec5+1dWmcDv0WH0qZLFK711sibNN5LutvnaiuH+w3Kr8Ylbw8gq2j0UBok"
  "FcMycUvOBd7nsYn/TUrOua3Nns+qKSJBy88IWSh2zHaGbjRYujyWSTjlPELJ0H+5"
  "EV711qseo/omquskkwIDAQAB")
#Copy the output of the command inside ( ) in one line and remove all quotes.
#v=DKIM1; p= MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYArsr2...................

#Check the Logs
docker exec -it iredmail tail -f /var/log/dovecot.log
docker exec -it iredmail tail -f /var/log/mail.log


version: '3'
services:
  iredmail:
    image: iredmail/mariadb:stable
    container_name: iredmail
    env_file:
      - iredmail-docker.conf
    hostname: mail.mydomain.com
    ports:
      - "808:80"
      - "4433:443"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - /iredmail/data/backup-mysql:/var/vmail/backup/mysql
      - /iredmail/data/mailboxes:/var/vmail/vmail1
      - /iredmail/data/mlmmj:/var/vmail/mlmmj
      - /iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive
      - /iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy
      - /iredmail/data/custom:/opt/iredmail/custom
      - /iredmail/data/ssl:/opt/iredmail/ssl
      - /iredmail/data/mysql:/var/lib/mysql
      - /iredmail/data/clamav:/var/lib/clamav
      - /iredmail/data/sa_rules:/var/lib/spamassassin
      - /iredmail/data/postfix_queue:/var/spool/postfix
