services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "2376:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"

    extra_hosts:
      - "host.docker.internal:host-gateway"

  ssh-agent:
    image: jenkins/ssh-agent
