version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    restart: always

volumes:
  keycloak-data:
