  GNU nano 4.8                                compose.yaml
version: '3.8'
services:
  minio:
    image: quay.io/minio/minio
    restart: always
    ports:
     - "9010:9000"
     - "9090:9090"
    volumes:
     - ./data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: your_password
    command: server /data --console-address ":9090"
