version: '3.6'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"
    container_name: mssql
    hostname: mssql
    volumes:
      - mssql_data:/var/opt/mssql
      - mssql_logs:/var/opt/sqlserver
    restart: unless-stopped

volumes:
  mssql_data:
  mssql_logs:
